# 介绍
Numpy是Python语言科学计算的核心库;Numpy主要提供高性能的多维对象数组
(array),以及用于计算array的工具。

## 主要特性:
- a powerful N-dimensional array object (高性能N维array object)
- sophisticated (broadcasting) functions (广播函数)
- tools for integrating C/C++ and Fortran code (多语言接口工具)
- useful linear algebra, Fourier transform, and random number capabilities (线代，傅里叶变换，随机数等数学功能)

In [2]:
# 导入numpy的方式:
import numpy as np # 用得最多 
# from numpy import *
# import numpy

## Array:数组
一个numpy数组是一个由不同数值组成的网格。网格中的数据都是同一种数据类型，可以通过非负整型数的元组来访问。维度的数量被称为数组的阶，数组的大小是一个由整型数构成的元组，可以描述数组不同维度上的大小。

- Numpy的数组，是一个值格
- 包含的元素有相同的类型
- 由一个非负数组成元素的元组来索引数组中的元素(当然可以由负数索引)
- 数组的秩(rank):数组维度的个数
- 数组的形状(shape):由元组中的整数元素来表示数组每一个维度的长度(size)

我们可以从列表创建数组，然后利用方括号访问其中的元素：

# 创建数组(Array Creation()
- Conversion from other Python structures (e.g., lists, tuples) (由其他集合创建)
- Intrinsic numpy array array creation objects (e.g., arange, ones, zeros, etc.) (本征numpy创建方式)
- Reading arrays from disk, either from standard or custom formats (从硬盘上读取)
- Creating arrays from raw bytes through the use of strings or buffers (由raw 字节(通过字符串缓冲器)创建)  Use of special library functions (e.g., random) (其他库函数手动比如:random函数)

In [3]:
# 创建一个一维数组
a = np.array([1, 2, 3])

In [4]:
print(a)
print(type(a)) # 类型
print(a.ndim)  # 秩,用.ndim查看。
print(a.shape) #
print(a[0], a[1], a[2])

[1 2 3]
<class 'numpy.ndarray'>
1
(3,)
1 2 3


In [5]:
a[0]=5 # 修改数组中的一个元素
print(a)

[5 2 3]


In [6]:
# 创建一个二维数组
b = np.array([[1,2,3],[4,5,6]]) 
# b = np.array(([1,2,3],[4,5,6])) 
# b = np.array(((1,2,3),(4,5,6)) 
print(b) 
print(b.ndim) 
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

[[1 2 3]
 [4 5 6]]
2
(2, 3)
1 2 4


## 思考题：创建一个三维数组
对多维数组进一步理解

In [72]:
a = np.ones([2,2,2])
print(a)
print('*'*10)

a = np.ones([2,2,3])
print(a)
print('*'*10)

a = np.ones([2,3,2])
print(a)
print('*'*10)

a = np.ones([3,2,2])
print(a)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
**********
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
**********
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
**********
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


从上面的代码可以看出，三维情况创建时后面2个参数可以看做是创建二维数组，第1个参数看做创建的二维数组的个数，所以创建时输入的参数为2,3,2时，就相当于创建了2个3行2列的二维数组。

In [62]:
# 创建一个三维数组的方法2
c= np.ones([2,2,3,3,5]) 
print(c)
print(c.ndim) 
print(c.shape)
print(c[0,1,1])

[[[[[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]]


  [[[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]]]



 [[[[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]]


  [[[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]]]]
5
(2, 2, 3, 3, 5)
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [71]:
# 创建一个三维数组的方法，太复杂
c= np.array([[[1,2],[3,4],[5,6]],[[1,2],[3,4],[5,6]]])
print(c)
print(c.ndim) 
print(c.shape)
print(c[0,1,1])

[[[1 2]
  [3 4]
  [5 6]]

 [[1 2]
  [3 4]
  [5 6]]]
3
(2, 3, 2)
4


其他数组相关方法，请查看[文档](https://numpy.org/doc/1.18/user/basics.creation.html#arrays-creation)

Numpy还提供了很多其他创建数组的方法：

In [15]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
print("\n")             #          [ 0.  0.]]"

b = np.ones((1,2))   # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"
print("\n")

c = np.full((2,2), 8) # Create a constant array
print(c)               # Prints "[[ 7.  7.]
print("\n")              #          [ 7.  7.]]"

d = np.eye(4)        # Create a 2x2 identity matrix（对角矩阵）
print(d)              # Prints "[[ 1.  0.]
print("\n")             #          [ 0.  1.]]"
    
# 这里就应该又怒疑问，这是什么？要学会搜索：https://blog.csdn.net/m0_37393514/article/details/81455915
# 使用 shift+tab 可以查看用法

e = np.random.random((2,2)) # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                            #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]


[[1. 1.]]


[[8 8]
 [8 8]]


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


[[0.4899064  0.78564601]
 [0.7987257  0.52563411]]


## 一、np.eye()
函数的原型：`numpy.eye(N,M=None,k=0,dtype=<class 'float'>,order='C)`

返回的是一个二维2的数组(N,M)，对角线的地方为1，其余的地方为0.

### 参数介绍：

（1）N:int型，表示的是输出的行数

（2）M：int型，可选项，输出的列数，如果没有就默认为N

（3）k：int型，可选项，对角线的下标，默认为0表示的是主对角线，负数表示的是低对角，正数表示的是高对角。

（4）dtype：数据的类型，可选项，返回的数据的数据类型

（5）order：{‘C’，‘F'}，可选项，也就是输出的数组的形式是按照C语言的行优先’C'，还是按照Fortran形式的列优先‘F'存储在内存中

### 案例：（普通的用法）

In [20]:
import numpy as np
 
a=np.eye(3)
print(a)
print("\n")
 
a=np.eye(4,k=1)
print(a)
print("\n")

a=np.eye(4,k=-1)
print(a)
print("\n")

a=np.eye(4,k=-3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]]


# 访问数组
Numpy提供了多种访问数组的方法。

## 切片
和Python列表类似，numpy数组可以使用切片语法。因为数组可以是多维的，所以你必须为每个维度指定好切片。

In [75]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3] # 注意左开右闭，从0开始
print(b)

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
77


In [44]:
import pandas as pd
a = [1,2,3,4]
print(pd.DataFrame(a))
b = a[:]
b[0] = 0
print(a)
print(b)

i = np.array([3,0])
print(i)
j = np.array([0,4])
print(j)
print(i.dot(j))

   0
0  1
1  2
2  3
3  4
[1, 2, 3, 4]
[0, 2, 3, 4]
[3 0]
[0 4]
0


In [38]:
import numpy as nop
a = np.array([[1,2,3,4],[4,3,2,1],[1,2,3,4]])
b = np.array(a[0:1,:3])
b[0,0]=8888
print(a)
print(b)

c = a[[0,2,1,1,1],[1,2,3,1,2]]
print(c.shape)

[[1 2 3 4]
 [4 3 2 1]
 [1 2 3 4]]
[[8888    2    3]]
(5,)


## 习题

In [76]:
m = np.arange(36).reshape([2,3,2,3]) # 变维函数
print(m)

[[[[ 0  1  2]
   [ 3  4  5]]

  [[ 6  7  8]
   [ 9 10 11]]

  [[12 13 14]
   [15 16 17]]]


 [[[18 19 20]
   [21 22 23]]

  [[24 25 26]
   [27 28 29]]

  [[30 31 32]
   [33 34 35]]]]


In [78]:
print(m[1,:,:,:])
print(m[:,1,:,:])
print(m[:,:,1,:])
print(m[:,:,:,1])

[[[18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]]]
[[[ 6  7  8]
  [ 9 10 11]]

 [[24 25 26]
  [27 28 29]]]
[[[ 3  4  5]
  [ 9 10 11]
  [15 16 17]]

 [[21 22 23]
  [27 28 29]
  [33 34 35]]]
[[[ 1  4]
  [ 7 10]
  [13 16]]

 [[19 22]
  [25 28]
  [31 34]]]


## 习题解读
前面`print(m)`很好理解~

然后print m[1,：,：,：]，：代表默认值（就是一开始你输入时指定的值），这句代码相当于输出2个包中的第1个包（从0开始计数），这个包里面有3个小包，小包里面是2*3的二维数组，所以结果就是上面的~

然后print m[：,1,：,：]，相当于输出2个大包，每个大包输出第1个小包，小包里面是2*3的二维数组

然后print m[：,：,1,：]，相当于输出2个大包，每个大包输出3个小包，小包里面是二维数组的第1行

然后print m[：,：,：,1]，相当于输出2个大包，每个大包输出3个小包，小包里面是1*2的一维数组

其他结果可以自己去试试~


## 整型数组访问
当我们使用切片语法访问数组时，得到的总是原数组的一个子集。整型数组访问允许我们利用其它数组的数据构建一个新的数组：

In [80]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

# An example of integer array indexing.
# The returned array will have shape (3,) and 
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
[1 4 5]
[2 2]
[2 2]


## 布尔型数组访问
布尔型数组访问可以让你选择数组中任意元素。通常，这种访问方式用于选取数组中满足某些条件的元素，举例如下：

In [81]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                    #          [ True  True]
                    #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


为了教程的简介，有很多数组访问的细节我们没有详细说明，可以查看[文档](https://numpy.org/doc/1.18/reference/arrays.indexing.html)

# 合并数组
## np.vstack() 上下合并

In [101]:
import numpy as np
A = np.array([1,1,1])
B = np.array([2,2,2])
         
print(np.vstack((A,B)))    # vertical stack 
"""
[[1,1,1]
 [2,2,2]]
"""
 
C = np.vstack((A,B))      
print(A.shape,C.shape)
 
# (3,) (2,3)

[[1 1 1]
 [2 2 2]]
(3,) (2, 3)


## np.hstack() 左右合并

In [102]:
D = np.hstack((A,B))       # horizontal stack
 
print(D)
# [1,1,1,2,2,2]
 
print(A.shape,D.shape)
# (3,) (6,)

[1 1 1 2 2 2]
(3,) (6,)


# 分割数组
## 纵向分割

In [104]:
import numpy as np
A = np.arange(12).reshape((3, 4))
"""
array([[ 0,  1,  2,  3],
    [ 4,  5,  6,  7],
    [ 8,  9, 10, 11]])
"""
 
print(np.split(A, 2, axis=1))
"""
[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]
"""

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


'\n[array([[0, 1],\n        [4, 5],\n        [8, 9]]), array([[ 2,  3],\n        [ 6,  7],\n        [10, 11]])]\n'

## 横向分割

In [105]:
print(np.split(A, 3, axis=0))
# [array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


## 等量分割
在Numpy里还有`np.vsplit()`与`np.hsplit()`方式可用。vertical可理解为垂直方向的操作，horizontal可理解为水平方向的操作。注意：也必须为等量分割。

In [107]:
print(np.vsplit(A, 3)) #等于 print(np.split(A, 3, axis=0))
 
# [array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
 
 
print(np.hsplit(A, 2)) #等于 print(np.split(A, 2, axis=1))
"""
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]
"""

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


'\n[array([[0, 1],\n       [4, 5],\n       [8, 9]]), array([[ 2,  3],\n        [ 6,  7],\n        [10, 11]])]\n'

## 不等量分割
上述均为等量分割，若为不等量时，如下：

In [108]:
print(np.array_split(A, 3, axis=1))
"""
[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2],
        [ 6],
        [10]]), array([[ 3],
        [ 7],
        [11]])]
"""

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


'\n[array([[0, 1],\n        [4, 5],\n        [8, 9]]), array([[ 2],\n        [ 6],\n        [10]]), array([[ 3],\n        [ 7],\n        [11]])]\n'

# 数据类型
每个Numpy数组都是数据类型相同的元素组成的网格。Numpy提供了很多的数据类型用于创建数组。当你创建数组的时候，Numpy会尝试猜测数组的数据类型，你也可以通过参数直接指定数据类型，例子如下：

In [ ]:
import numpy as np

x = np.array([1, 2])  # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])  # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)  # Force a particular datatype
print(x.dtype)                        # Prints "int64"

更多细节查看[文档](https://numpy.org/doc/1.18/reference/arrays.dtypes.html)

# 数组计算
基本数学计算函数会对数组中元素逐个进行计算，既可以利用操作符重载，也可以使用函数方式：

In [88]:
import numpy as np

x = np.array([[1,2],[3,49]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x)
print(y)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x)) # 开平方根

[[ 1.  2.]
 [ 3. 49.]]
[[5. 6.]
 [7. 8.]]
[[ 6.  8.]
 [10. 57.]]
[[ 6.  8.]
 [10. 57.]]
[[-4. -4.]
 [-4. 41.]]
[[-4. -4.]
 [-4. 41.]]
[[  5.  12.]
 [ 21. 392.]]
[[  5.  12.]
 [ 21. 392.]]
[[0.2        0.33333333]
 [0.42857143 6.125     ]]
[[0.2        0.33333333]
 [0.42857143 6.125     ]]
[[1.         1.41421356]
 [1.73205081 7.        ]]


和MATLAB不同，*是元素逐个相乘，而不是矩阵乘法。在Numpy中使用dot来进行矩阵乘法：

In [91]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x)
print(y)

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
# print(v.dot(w))
# print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
# print(x.dot(v))
# print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y)) # 5+14=19，1*6
# print(np.dot(x, y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]


Numpy提供了很多计算数组的函数，其中最常用的一个是sum：

In [93]:
import numpy as np

x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


想要了解更多函数，可以查看[文档](https://numpy.org/doc/1.18/reference/routines.math.html)。

除了计算，我们还常常改变数组或者操作其中的元素。其中将矩阵转置是常用的一个，在Numpy中，使用T来转置矩阵：

In [94]:
import numpy as np

x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
           #          [3 4]]"
print(x.T)  # Prints "[[1 3]
           #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


# 广播Broadcasting
广播是一种强有力的机制，它让Numpy可以让不同大小的矩阵在一起进行数学计算。我们常常会有一个小的矩阵和一个大的矩阵，然后我们会需要用小的矩阵对大的矩阵做一些计算。

举个例子，如果我们想要把一个向量加到矩阵的每一行，我们可以这样做：

In [95]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


这样是行得通的，但是当x矩阵非常大，利用循环来计算就会变得很慢很慢。我们可以换一种思路：

In [96]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)                # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise
print(y)  # Prints "[[ 2  2  4
         #          [ 5  5  7]
         #          [ 8  8 10]
         #          [11 11 13]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy广播机制可以让我们不用创建vv，就能直接运算，看看下面例子：

In [97]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
         #          [ 5  5  7]
         #          [ 8  8 10]
         #          [11 11 13]]"

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


## 图片解读
![](https://pptwinpics.oss-cn-beijing.aliyuncs.com/numpy-guangbo_20200213111309.png)

## 注意

对两个数组使用广播机制要遵守下列规则：

- 如果数组的秩不同，使用1来将秩较小的数组进行扩展，直到两个数组的尺寸的长度都一样。
- 如果两个数组在某个维度上的长度是一样的，或者其中一个数组在该维度上长度为1，那么我们就说这两个数组在该维度上是相容的。
- 如果两个数组在所有维度上都是相容的，他们就能使用广播。
- 如果两个输入数组的尺寸不同，那么注意其中较大的那个尺寸。因为广播之后，两个数组的尺寸将和那个较大的尺寸一样。
- 在任何一个维度上，如果一个数组的长度为1，另一个数组长度大于1，那么在该维度上，就好像是对第一个数组进行了复制。

如果上述解释看不明白，可以读一读[文档](https://numpy.org/doc/1.18/user/basics.broadcasting.html)和这个[解释](http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc)。强烈推荐阅读文档中的例子。

支持广播机制的函数是全局函数。哪些是全局函数可以在文档中查找。

下面是一些广播机制的使用：

In [99]:
import numpy as np

# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)

# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


广播机制能够让你的代码更简洁更迅速，能够用的时候请尽量使用！

# Numpy文档
这篇教程涉及了你需要了解的numpy中的一些重要内容，但是numpy远不止如此。可以查阅[numpy文献](https://numpy.org/doc/1.18/reference/)来学习更多。